
### Get User By UserID
GET http://localhost:3000/api/_developer/password/630 HTTP/1.1 
content-type: application/json

### Change Password By UserID
PUT http://localhost:3000/api/_developer/password/630 HTTP/1.1 
content-type: application/json

{
    "password": "Pravin1975"
}